# Generated by Django 4.0.3 on 2022-11-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('correoUsr', models.CharField(max_length=70)),
                ('admin', models.BooleanField(default=False)),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
    ]
