# Generated by Django 4.0.3 on 2022-11-09 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('idReunion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=50)),
                ('tipoReunion', models.CharField(max_length=50)),
                ('asistencia', models.BooleanField(verbose_name='Asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('correoUsr', models.CharField(max_length=70)),
                ('admin', models.BooleanField(default=False)),
                ('contrasena', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateTimeField(verbose_name='fechaNacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.usuario')),
                ('documentoAsociado', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=70)),
                ('ciudad', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.usuario')),
                ('documentoCliente', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='DocumentoC')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('asociadoVinculado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asociado')),
            ],
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='ReunionPresencial',
            fields=[
                ('reunion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.reunion')),
                ('sitio', models.CharField(max_length=50)),
                ('costo', models.IntegerField(verbose_name='Costo')),
            ],
            bases=('api.reunion',),
        ),
        migrations.CreateModel(
            name='ReunionVirtual',
            fields=[
                ('reunion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.reunion')),
                ('enlace', models.IntegerField(primary_key=True, serialize=False, verbose_name='Enlace')),
            ],
            bases=('api.reunion',),
        ),
        migrations.AddField(
            model_name='reunion',
            name='asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asociado'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('solicitudPrestamo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estadoPrestamo', models.BooleanField(verbose_name='EstadoPrestamo')),
                ('interes', models.FloatField(verbose_name='Interes')),
                ('comision', models.IntegerField(verbose_name='Comision')),
                ('codeudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asociado')),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('idMulta', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('costo', models.IntegerField()),
                ('estadoMulta', models.BooleanField(default=False)),
                ('idAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asociado')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaManejo',
            fields=[
                ('idCuotaManejo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaComienzo', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('tasaInteres', models.IntegerField()),
                ('idAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asociado')),
            ],
        ),
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('idAhorro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=50)),
                ('monto', models.FloatField()),
                ('firmaDigital', models.CharField(max_length=50)),
                ('tipoConsignacion', models.CharField(max_length=50)),
                ('idAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asociado')),
            ],
        ),
    ]
