# Generated by Django 4.0.3 on 2023-01-04 04:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=80, unique=True)),
                ('username', models.CharField(max_length=45)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente'), ('asociado', 'Asociado')], max_length=20)),
                ('documento', models.CharField(max_length=15, unique=True)),
                ('ciudad', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('ocupacion', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('fechaNacimiento', models.DateField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='CuotaManejo',
            fields=[
                ('idCuotaManejo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaComienzo', models.DateField()),
                ('fechaFin', models.DateField()),
                ('tasaInteres', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('idReunion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=30)),
                ('motivo', models.CharField(max_length=60)),
                ('tipoReunion', models.CharField(max_length=10)),
                ('asistencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReunionPresencial',
            fields=[
                ('reunion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.reunion')),
                ('sitio', models.CharField(max_length=50)),
                ('costo', models.IntegerField()),
            ],
            bases=('api.reunion',),
        ),
        migrations.CreateModel(
            name='ReunionVirtual',
            fields=[
                ('reunion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.reunion')),
                ('enlace', models.CharField(max_length=50)),
                ('costo', models.IntegerField()),
            ],
            bases=('api.reunion',),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('solicitudPrestamo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField(default=datetime.date(2023, 1, 4))),
                ('estadoPrestamo', models.BooleanField(default=False)),
                ('interes', models.FloatField()),
                ('comision', models.IntegerField()),
                ('codeudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamoCodeudor', to=settings.AUTH_USER_MODEL)),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamoDeudor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prestamo',
                'verbose_name_plural': 'prestamos',
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('idMulta', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('costo', models.IntegerField()),
                ('estadoMulta', models.BooleanField()),
                ('asociadoReferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociadoReferente', to=settings.AUTH_USER_MODEL, to_field='documento')),
            ],
        ),
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('idAhorro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date(2023, 1, 4))),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('monto', models.IntegerField()),
                ('firmaDigital', models.CharField(max_length=200)),
                ('tipoConsignacion', models.CharField(max_length=200)),
                ('DocAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='documento')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('idAbono', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField(default=datetime.date(2023, 1, 4))),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('abona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='documento')),
                ('cuentaAhorro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ahorro')),
                ('idPrestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestamo')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
            },
        ),
    ]
