# Generated by Django 4.0.3 on 2022-12-10 20:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abono',
            options={'verbose_name': 'Abono', 'verbose_name_plural': 'Abonos'},
        ),
        migrations.AddField(
            model_name='abono',
            name='Abona',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 10)),
        ),
        migrations.AlterField(
            model_name='user',
            name='documento',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
