# Generated by Django 4.0.3 on 2022-12-29 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multa',
            name='idAsociado',
        ),
    ]
