# Generated by Django 4.0.3 on 2022-11-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.usuario')),
                ('idAsociado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=70)),
                ('ciudad', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.usuario')),
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('asociadoVinculado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asociado')),
            ],
            bases=('api.usuario',),
        ),
    ]
