# Generated by Django 4.0.3 on 2022-11-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_asociado_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
