# Generated by Django 4.0.3 on 2022-12-29 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_multa_idasociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='idAsociado',
            field=models.ForeignKey(default='123456789', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='documento'),
            preserve_default=False,
        ),
    ]
