# Generated by Django 4.0.3 on 2022-11-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_asociado_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('idReunion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=30)),
                ('motivo', models.CharField(max_length=60)),
                ('tipoReunion', models.CharField(max_length=10)),
                ('asistencia', models.BooleanField(default=False)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asociado')),
            ],
        ),
        migrations.CreateModel(
            name='ReunionPresencial',
            fields=[
                ('reunion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.reunion')),
                ('sitio', models.CharField(max_length=50)),
                ('costo', models.IntegerField()),
            ],
            bases=('api.reunion',),
        ),
        migrations.CreateModel(
            name='ReunionVirtual',
            fields=[
                ('reunion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.reunion')),
                ('enlace', models.CharField(max_length=50)),
                ('costo', models.IntegerField()),
            ],
            bases=('api.reunion',),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('solicitudPrestamo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estadoPrestamo', models.BooleanField(default=False)),
                ('interes', models.FloatField()),
                ('comision', models.IntegerField()),
                ('codeudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asociado')),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('idMulta', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('costo', models.IntegerField()),
                ('estadoMulta', models.BooleanField()),
                ('idAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asociado')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaManejo',
            fields=[
                ('idCuotaManejo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaComienzo', models.DateField()),
                ('fechaFin', models.DateField()),
                ('tasaInteres', models.IntegerField()),
                ('idAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asociado')),
            ],
        ),
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('idAhorro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.IntegerField()),
                ('firmaDigital', models.CharField(max_length=200)),
                ('tipoConsignacion', models.CharField(max_length=200)),
                ('idAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asociado')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('idAbono', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('idPrestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestamo')),
            ],
        ),
    ]
