# Generated by Django 4.0.3 on 2022-12-11 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ahorro_idasociado_alter_abono_abona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='abona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='documento'),
        ),
    ]
