# Generated by Django 4.0.3 on 2022-12-11 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_abono_abona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahorro',
            name='idAsociado',
        ),
        migrations.AddField(
            model_name='ahorro',
            name='DocAsociado',
            field=models.ForeignKey(default=123456789, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='documento'),
            preserve_default=False,
        ),
    ]
