# Generated by Django 4.0.3 on 2022-12-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_abono_options_abono_abona_ahorro_docasociado_and_more'),
        ('api', '0006_remove_ahorro_idasociado_ahorro_docasociado'),
    ]

    operations = [
    ]
