# Generated by Django 4.0.3 on 2022-12-18 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_abono_fecha_alter_ahorro_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='cuentaAhorro',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ahorro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 18)),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 18)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 18)),
        ),
    ]
