# Generated by Django 4.0.3 on 2022-12-29 02:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_abono_cuentaahorro_alter_abono_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'prestamo',
                     'verbose_name_plural': 'prestamos'},
        ),
        migrations.AddField(
            model_name='multa',
            name='asociadoReferente',
            field=models.ForeignKey(default="123456789", on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, to_field='documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 29)),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='DocAsociado',
            field=models.ForeignKey(default="123456789",
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='documento'),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 29)),
        ),
        migrations.AlterField(
            model_name='multa',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 12, 29)),
        ),
    ]
