# Generated by Django 4.0.3 on 2022-12-29 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_prestamo_options_multa_asociadoreferente_and_more'),
        ('api', '0010_alter_prestamo_options_prestamo_codeudor_and_more'),
    ]

    operations = [
    ]
