# Generated by Django 4.0.3 on 2022-12-29 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20221228_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorro',
            name='DocAsociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='documento'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='solicitudPrestamo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
