# Generated by Django 4.0.3 on 2023-01-04 01:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_reunionvirtual_costo_reunion_fechacreacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunionpresencial',
            name='id_reunion',
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 1, 4)),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 1, 4)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 1, 4)),
        ),
        migrations.AlterField(
            model_name='reunionpresencial',
            name='costo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
