# Generated by Django 4.0.3 on 2023-01-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_reunion_fechacreacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunionvirtual',
            name='id_reunion',
        ),
    ]
