# Generated by Django 4.0.3 on 2023-01-05 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_abono_fecha_alter_ahorro_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='abona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='documento'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='cuentaAhorro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ahorro'),
        ),
    ]
