# Generated by Django 4.0.3 on 2023-01-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_abono_fecha_alter_ahorro_fecha_and_more'),
        ('api', '0019_alter_abono_abona_alter_abono_cuentaahorro'),
    ]

    operations = [
    ]
