# Generated by Django 4.0.3 on 2023-01-05 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20230105_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='multa',
            name='asociadoReferente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociadoReferente', to=settings.AUTH_USER_MODEL, to_field='documento'),
        ),
    ]
