# Generated by Django 4.0.3 on 2023-01-06 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_abono_fecha_alter_ahorro_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 1, 6)),
        ),
    ]
