# Generated by Django 4.0.3 on 2023-01-08 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_cliente_asociadovinculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorro',
            name='autorizado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 1, 8)),
        ),
    ]
