# Generated by Django 4.0.3 on 2023-01-08 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_ahorro_autorizado_alter_prestamo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='idSancion',
            field=models.ForeignKey(
                default=25, on_delete=django.db.models.deletion.CASCADE, to='api.multa'),
            preserve_default=False,
        ),
    ]
