# Generated by Django 4.0.3 on 2023-01-09 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_abono_idsancion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='cuentaAhorro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ahorro'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='idPrestamo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.prestamo'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='idSancion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.multa'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 1, 9)),
        ),
    ]
