# Generated by Django 4.0.3 on 2023-01-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_abono_cuentaahorro_alter_abono_idprestamo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abono',
            old_name='idPrestamo',
            new_name='cuentaPrestamo',
        ),
        migrations.RenameField(
            model_name='abono',
            old_name='idSancion',
            new_name='cuentaSancion',
        ),
    ]
