# Generated by Django 4.0.3 on 2023-01-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_multa_montopagado_alter_prestamo_fecha'),
        ('api', '0027_rename_idprestamo_abono_cuentaprestamo_and_more'),
    ]

    operations = [
    ]
