# Generated by Django 4.0.3 on 2023-01-09 22:57
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20230109_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='asociadoReferente',
            field=models.ForeignKey(default="123456789", on_delete=django.db.models.deletion.CASCADE,
                                    related_name='asociadoReferente', to=settings.AUTH_USER_MODEL, to_field='documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abono',
            name='cuentaAhorro',
            field=models.ForeignKey(
                default=4, on_delete=django.db.models.deletion.CASCADE, to='api.ahorro'),
            preserve_default=False,
        ),
    ]
