# Generated by Django 4.0.3 on 2023-01-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_solicitudprestamo_prestamo_idprestamo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abono',
            name='cuentaPrestamo',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
