# Generated by Django 4.0.3 on 2023-01-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_prestamo_idprestamo_alter_prestamo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
