# Generated by Django 4.0.3 on 2023-01-11 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_prestamo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='cuentaPrestamo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.prestamo'),
        ),
    ]
