# Generated by Django 4.0.3 on 2023-01-11 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_abono_cuentaprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='cuentaAhorro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ahorro'),
        ),
    ]
