# Generated by Django 4.0.3 on 2023-01-24 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='asociadoVinculado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_asociadoVinculado', to=settings.AUTH_USER_MODEL, to_field='documento'),
        ),
    ]
