# Generated by Django 4.0.3 on 2023-01-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_cliente_asociadovinculado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('asociadoVinculado',)},
        ),
    ]
